/** @type {import('tailwindcss').Config} */
// Design tokens mirrored verbatim from the Stitch HTML references
// (design-reference/) so those screens port to JSX 1:1. See DESIGN.md.
export default {
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'inverse-primary': '#d7c1c8',
        'tertiary-fixed': '#eae4b1',
        'inverse-surface': '#303030',
        'primary-fixed-dim': '#d7c1c8',
        'on-error': '#ffffff',
        'secondary-fixed': '#d6e5ef',
        tertiary: '#636037',
        'surface-dim': '#dcd9d9',
        'surface-container-lowest': '#ffffff',
        background: '#fbf9f8',
        'on-primary-fixed-variant': '#524249',
        'on-error-container': '#93000a',
        'on-tertiary-container': '#6e6b41',
        'error-container': '#ffdad6',
        'on-primary-container': '#76646b',
        error: '#ba1a1a',
        'secondary-fixed-dim': '#bac9d3',
        'tertiary-container': '#f2ecb8',
        'surface-container-high': '#eae8e7',
        'on-background': '#1b1c1c',
        'on-primary': '#ffffff',
        'on-secondary': '#ffffff',
        'on-tertiary': '#ffffff',
        'surface-container': '#f0eded',
        'on-surface': '#1b1c1c',
        'on-tertiary-fixed': '#1e1c00',
        'surface-container-highest': '#e4e2e1',
        'on-secondary-fixed': '#0f1d25',
        surface: '#fbf9f8',
        secondary: '#526069',
        primary: '#6b5a60',
        'surface-bright': '#fbf9f8',
        'inverse-on-surface': '#f3f0f0',
        'secondary-container': '#d3e2ed',
        'surface-container-low': '#f6f3f2',
        'on-surface-variant': '#4d4447',
        'on-secondary-container': '#56656e',
        'primary-container': '#fce4ec',
        outline: '#7f7478',
        'on-primary-fixed': '#25181e',
        'outline-variant': '#d0c3c7',
        'surface-tint': '#6b5a60',
        'tertiary-fixed-dim': '#cdc897',
        'on-tertiary-fixed-variant': '#4b4822',
        'surface-variant': '#e4e2e1',
        'on-secondary-fixed-variant': '#3b4951',
        'primary-fixed': '#f4dce4',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        base: '4px',
        xs: '8px',
        sm: '12px',
        gutter: '12px',
        md: '16px',
        lg: '24px',
        xl: '32px',
        'container-margin': '20px',
      },
      fontFamily: {
        sans: ['Plus Jakarta Sans', 'sans-serif'],
        'headline-xl': ['Plus Jakarta Sans'],
        'headline-lg': ['Plus Jakarta Sans'],
        'headline-lg-mobile': ['Plus Jakarta Sans'],
        'body-md': ['Plus Jakarta Sans'],
        'body-sm': ['Plus Jakarta Sans'],
        'label-lg': ['Plus Jakarta Sans'],
        'label-sm': ['Plus Jakarta Sans'],
      },
      fontSize: {
        'headline-xl': ['32px', { lineHeight: '40px', letterSpacing: '0', fontWeight: '700' }],
        'headline-lg': ['24px', { lineHeight: '32px', letterSpacing: '0', fontWeight: '600' }],
        'headline-lg-mobile': ['22px', { lineHeight: '28px', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-lg': ['14px', { lineHeight: '16px', letterSpacing: '0', fontWeight: '600' }],
        'label-sm': ['12px', { lineHeight: '14px', fontWeight: '500' }],
      },
    },
  },
  plugins: [],
}
