export const queryKeys = {
  entry: (date) => ['entries', 'me', 'date', date],
  entries: (month) => ['entries', 'me', month],
  entrySummary: (month) => ['entries', 'summary', month],
  friendEntries: (friendId, month) => ['entries', 'friend', friendId, month],
  friends: ['friends', 'list'],
  pendingFriends: ['friends', 'pending'],
  feed: (includeSelf = false) => ['feed', { includeSelf }],
  comments: (entryId) => ['feed', 'comments', entryId],
  session: ['auth', 'session'],
  profile: ['profile'],
  friendProfile: (id) => ['users', 'profile', id],
  notifications: ['notifications', 'list'],
  unreadCount: ['notifications', 'unreadCount'],
  unreadAnnouncements: ['announcements', 'unread'],
  adminAnnouncements: ['admin', 'announcements'],
}
